### ISSUE TITLE
improve color adjustement for background color

### ISSUE THREAD

**Issue by fabfabBesnard** [Raphalex46/3d-plantviewer#17]
Find a more adapted picker
like RVBA/wheel ?
example from inkscape soft:
![image](https://user-images.githubusercontent.com/20174786/84368434-dc434000-abd5-11ea-9135-c69cfe2d6664.png)

#BetterPlantVis
#branch: background color
https://github.com/orgs/romi/projects/6#card-39903076

**Comment by Raphalex46** [comment]
Changed in 5d7c7434d51cac0458b75ba71a6a38a997f173f6
